version: "3"

services:
  registry:
    build: registry
    volumes:
      - "${REGISTRY_HOME}:/var/lib/registry/"
      - "${HTPASSWD_PATH}:/auth/htpasswd"
      - "./letsencrypt/cachefile:/letsencrypt/cachefile"
    ports:
      - "443:5000"
    environment:
      - REGISTRY_HTTP_TLS_LETSENCRYPT_CACHEFILE=/letsencrypt/cachefile
      - REGISTRY_HTTP_TLS_LETSENCRYPT_EMAIL=test@emawind.com
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
    networks:
      default:
        aliases: 
        - registry-srv
    restart: "unless-stopped"