version: "3"

services:
  registry:
    build: registry
    volumes:
      - "${REGISTRY_HOME}:/var/lib/registry/"
    ports:
      - "${REGISTRY_PORT}:5000"
    networks:
      default:
        aliases: 
        - registry-srv
    restart: "unless-stopped"