version: "3"

services:
  registry:
    build: registry
    volumes:
      - "${REGISTRY_HOME}:/var/lib/registry/"
      - "${HTPASSWD_PATH}:/auth/htpasswd"
      - "./letsencrypt/cachefile:/letsencrypt/cachefile"
    ports:
      - "${REGISTRY_PORT}:5000"
    environment:
      - REGISTRY_HTTP_TLS_LETSENCRYPT_CACHEFILE=/letsencrypt/cachefile
      - REGISTRY_HTTP_TLS_LETSENCRYPT_EMAIL=pmis@sangah.com
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
    networks:
      default:
        aliases: 
        - registry-srv
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: "unless-stopped"